import { writeFileSync } from "fs"
import { join } from "path"

const dir = join("src", "generated", "prisma", "client")

// Re-export only from client.ts — it's the main entry point generated by Prisma 7.
// Don't wildcard re-export all files (browser.ts, models.ts, etc.) as they have
// overlapping exports that cause TS2308 duplicate member errors.
writeFileSync(join(dir, "index.ts"), 'export * from "./client"\n')
