"""Initialize a git repo and optionally push to GitHub.

Creates a clean initial commit with a descriptive message listing the
stack and versions, then optionally creates a private GitHub repo.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def run_cmd(cmd: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess:
    """Run a command and return the result."""
    return subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        check=check,
        timeout=30,
    )


def init_git(
    project_dir: Path,
    project_name: str,
    template_name: str,
    stack_description: str,
    *,
    no_github: bool = False,
) -> str | None:
    """Initialize git repo, create initial commit, optionally push to GitHub.

    Returns the GitHub repo URL if created, or None if local-only.
    """
    project_dir = Path(project_dir).resolve()

    # Git init
    run_cmd(["git", "init"], project_dir)

    # Stage all files
    run_cmd(["git", "add", "-A"], project_dir)

    # Create initial commit
    commit_msg = (
        f"Initial scaffold: {template_name} monorepo\n"
        f"\n"
        f"Stack: {stack_description}\n"
        f"Generated by create-repo skill."
    )
    run_cmd(["git", "commit", "-m", commit_msg], project_dir)

    if no_github:
        return None

    # Check if gh is authenticated
    auth_check = run_cmd(["gh", "auth", "status"], project_dir, check=False)
    if auth_check.returncode != 0:
        raise RuntimeError("GitHub CLI is not authenticated. Run `gh auth login` first.")

    # Check if repo already exists
    repo_check = run_cmd(
        ["gh", "repo", "view", project_name, "--json", "url"],
        project_dir,
        check=False,
    )
    if repo_check.returncode == 0:
        raise RuntimeError(
            f"GitHub repo '{project_name}' already exists. "
            f"Choose a different name or use --no-github."
        )

    # Create repo and push
    result = run_cmd(
        ["gh", "repo", "create", project_name, "--private", "--source=.", "--push"],
        project_dir,
    )

    # Extract URL from output
    url = result.stdout.strip()
    if not url:
        # Try to get it from gh repo view
        view = run_cmd(
            ["gh", "repo", "view", "--json", "url", "-q", ".url"], project_dir, check=False
        )
        url = view.stdout.strip()

    return url or f"https://github.com/{project_name}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Initialize git repo and push to GitHub")
    parser.add_argument("project_dir", help="Path to the project directory")
    parser.add_argument("--project-name", required=True, help="Project name")
    parser.add_argument("--template", required=True, help="Template name used")
    parser.add_argument("--stack", required=True, help="Stack description for commit message")
    parser.add_argument("--no-github", action="store_true", help="Skip GitHub repo creation")
    args = parser.parse_args()

    try:
        url = init_git(
            Path(args.project_dir),
            args.project_name,
            args.template,
            args.stack,
            no_github=args.no_github,
        )
        if url:
            print(f"GitHub repo created: {url}")
        else:
            print("Git repo initialized (local only)")
    except (subprocess.CalledProcessError, RuntimeError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
