"""Initialize a git repo and optionally push to GitHub.

Creates a clean initial commit with a descriptive message listing the
stack and versions, then optionally creates a private GitHub repo.
"""

from __future__ import annotations

import argparse
import json as _json
import subprocess
import sys
import time
from pathlib import Path


def run_cmd(cmd: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess:
    """Run a command and return the result."""
    result = subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
        timeout=30,
    )
    if check and result.returncode != 0:
        cmd_str = " ".join(cmd)
        raise subprocess.CalledProcessError(
            result.returncode,
            cmd_str,
            output=result.stdout,
            stderr=result.stderr,
        )
    return result


def _raise_with_output(result: subprocess.CompletedProcess) -> None:
    """Raise a CalledProcessError with full stderr/stdout included in the message."""
    cmd_str = result.args if isinstance(result.args, str) else " ".join(result.args)
    stderr = result.stderr.strip()
    stdout = result.stdout.strip()
    detail = stderr or stdout or "(no output)"
    raise RuntimeError(f"Command failed (exit {result.returncode}): {cmd_str}\n{detail}")


def init_git(
    project_dir: Path,
    project_name: str,
    template_name: str,
    stack_description: str,
    *,
    no_github: bool = False,
    github_org: str | None = None,
) -> str | None:
    """Initialize git repo, create initial commit, optionally push to GitHub.

    Returns the GitHub repo URL if created, or None if local-only.
    Idempotent: safe to re-run if a prior attempt partially succeeded.
    """
    project_dir = Path(project_dir).resolve()

    commit_msg = (
        f"Initial scaffold: {template_name} monorepo\n"
        f"\n"
        f"Stack: {stack_description}\n"
        f"Generated by create-repo skill."
    )

    # Check if git is already initialized with commits (partial prior run)
    has_commits = run_cmd(["git", "rev-parse", "HEAD"], project_dir, check=False).returncode == 0

    if not has_commits:
        run_cmd(["git", "init"], project_dir)

    # Stage all files — always, so any changes since a partial run are included
    run_cmd(["git", "add", "-A"], project_dir)

    # Only commit if there's something staged (avoids "nothing to commit" on re-run)
    status = run_cmd(["git", "status", "--porcelain"], project_dir, check=False)
    if status.stdout.strip():
        run_cmd(["git", "commit", "-m", commit_msg], project_dir)

    if no_github:
        return None

    # Check if gh is authenticated
    auth_check = run_cmd(["gh", "auth", "status"], project_dir, check=False)
    if auth_check.returncode != 0:
        raise RuntimeError("GitHub CLI is not authenticated. Run `gh auth login` first.")

    # Determine the repo slug (org/name or just name)
    repo_slug = f"{github_org}/{project_name}" if github_org else project_name

    # Push to GitHub with retries — re-checks repo state each attempt so partial
    # prior runs (repo created, push failed) are handled without special-casing.
    _MAX_ATTEMPTS = 3
    last_error: Exception = RuntimeError("GitHub push failed (no attempts made)")
    for attempt in range(1, _MAX_ATTEMPTS + 1):
        repo_check = run_cmd(
            ["gh", "repo", "view", repo_slug, "--json", "url,isEmpty"],
            project_dir,
            check=False,
        )
        repo_exists = repo_check.returncode == 0
        repo_url: str | None = None

        if repo_exists:
            repo_info = _json.loads(repo_check.stdout)
            if not repo_info.get("isEmpty"):
                raise RuntimeError(
                    f"GitHub repo '{repo_slug}' already exists and has commits. "
                    "Choose a different name or use --no-github."
                )
            repo_url = repo_info.get("url") or f"https://github.com/{repo_slug}"

        try:
            if not repo_exists:
                # Create and push in one shot
                result = run_cmd(
                    ["gh", "repo", "create", repo_slug, "--private", "--source=.", "--push"],
                    project_dir,
                    check=False,
                )
                if result.returncode != 0:
                    _raise_with_output(result)
                url = result.stdout.strip()
                if not url:
                    view = run_cmd(
                        ["gh", "repo", "view", "--json", "url", "-q", ".url"],
                        project_dir,
                        check=False,
                    )
                    url = view.stdout.strip()
                return url or f"https://github.com/{repo_slug}"
            else:
                # Repo exists but empty — remote already configured, just push
                result = run_cmd(["git", "push", "-u", "origin", "main"], project_dir, check=False)
                if result.returncode != 0:
                    _raise_with_output(result)
                return repo_url or f"https://github.com/{repo_slug}"

        except (RuntimeError, subprocess.CalledProcessError) as e:
            last_error = e
            if attempt < _MAX_ATTEMPTS:
                wait = 2**attempt  # 2s, 4s
                print(
                    f"  GitHub push attempt {attempt}/{_MAX_ATTEMPTS} failed, "
                    f"retrying in {wait}s...",
                    file=sys.stderr,
                )
                time.sleep(wait)

    raise last_error


def main() -> None:
    parser = argparse.ArgumentParser(description="Initialize git repo and push to GitHub")
    parser.add_argument("project_dir", help="Path to the project directory")
    parser.add_argument("--project-name", required=True, help="Project name")
    parser.add_argument("--template", required=True, help="Template name used")
    parser.add_argument("--stack", required=True, help="Stack description for commit message")
    parser.add_argument("--no-github", action="store_true", help="Skip GitHub repo creation")
    parser.add_argument(
        "--github-org", help="GitHub org to create the repo under (defaults to authenticated user)"
    )
    args = parser.parse_args()

    try:
        url = init_git(
            Path(args.project_dir),
            args.project_name,
            args.template,
            args.stack,
            no_github=args.no_github,
            github_org=args.github_org,
        )
        if url:
            print(f"GitHub repo created: {url}")
        else:
            print("Git repo initialized (local only)")
    except (subprocess.CalledProcessError, RuntimeError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
